apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-gateway-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-gateway
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: p99_latency
        target:
          type: AverageValue
          averageValue: "500m" # 500ms 目标
