/* package main

import (
	"context"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"sync"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/keepalive"

	_ "net/http/pprof" //
	// --- 链路追踪相关核心依赖 ---
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
	"go.opentelemetry.io/otel/propagation"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.17.0"

	// 拦截器与插件
	irisv1  "my-go-gateway/gen/iris/v1"
	modelv1 "my-go-gateway/gen/model/v1"

	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
)

var (
	// 记录请求总数 (用于计算 QPS)
	httpRequestsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "http_requests_total",
			Help: "Total number of HTTP requests.",
		},
		[]string{"path", "status"},
	)
	// 记录请求耗时 (用于计算 P99 延迟)
	httpDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "http_request_duration_seconds",
			Help:    "Histogram of response latency for HTTP requests.",
			Buckets: []float64{.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10},
		},
		[]string{"path"},
	)

	grpcRequestDuration = prometheus.NewHistogramVec(
        prometheus.HistogramOpts{
			Name:    "grpc_request_duration_seconds",
			Help:    "Histogram of gRPC request duration.", // ← add this
			Buckets: prometheus.DefBuckets,
        },
        []string{"method", "status"},
    )

	// === 新增：大模型专属指标 ===
	// 记录生成的总 Token 数 (用于计算吞吐量 TPS)
	aiTokensTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "ai_generated_tokens_total",
			Help: "Total number of tokens generated by AI models.",
		},
		[]string{"model"},
	)
	// 记录大模型的纯推理耗时
	aiGenerationDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "ai_generation_duration_seconds",
			Help:    "Histogram of AI model purely generation duration.",
			// 针对大模型生成，桶的范围要设置得大一些 (0.5秒 到 60秒)
			Buckets: []float64{.5, 1, 2, 5, 10, 20, 30, 60},
		},
		[]string{"model"},
	)

)

func init() {
    prometheus.MustRegister(httpRequestsTotal)
    prometheus.MustRegister(httpDuration)
    prometheus.MustRegister(grpcRequestDuration)
    prometheus.MustRegister(aiTokensTotal)
    prometheus.MustRegister(aiGenerationDuration)
}

// 初始化 OpenTelemetry 追踪器
func initTracer() (*sdktrace.TracerProvider, error) {
	ctx := context.Background()

	jaegerEndpoint := os.Getenv("JAEGER_ENDPOINT")
	if jaegerEndpoint == "" {
		jaegerEndpoint = "localhost:4317" // local dev fallback
	}

	// 连接到 Docker Compose 中的 Jaeger 服务
	exporter, err := otlptracegrpc.New(ctx,
		otlptracegrpc.WithEndpoint(jaegerEndpoint),
		otlptracegrpc.WithInsecure(),
	)
	if err != nil {
		return nil, err
	}

	tp := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(exporter),
		sdktrace.WithResource(resource.NewWithAttributes(
			semconv.SchemaURL,
			semconv.ServiceNameKey.String("go-gateway"),
		)),
	)

	otel.SetTracerProvider(tp)
	// 关键：设置全局传播器，这样 otelgrpc 才能把 ID 传出去
	otel.SetTextMapPropagator(propagation.TraceContext{})
	return tp, nil
}

func main() {

	go func() {
		// 建议使用独立端口，避免干扰业务逻辑
		slog.Info("pprof running on http://localhost:6060/debug/pprof")
		if err := http.ListenAndServe(":6060", nil); err != nil {
			slog.Error("pprof failed", "error", err)
		}
	}()

	// 1. 初始化链路追踪
	tp, err := initTracer()
	if err != nil {
		slog.Error("failed to initialize tracer", "error", err)
		os.Exit(1)
	}
	defer func() { _ = tp.Shutdown(context.Background()) }()

	addr := os.Getenv("AI_SERVICE_ADDR")
	if addr == "" {
		addr = "localhost:50051" // local dev fallback
	}
	conn, err := grpc.NewClient(
		addr,
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithStatsHandler(otelgrpc.NewClientHandler()),
		grpc.WithDefaultCallOptions(
			grpc.MaxCallRecvMsgSize(50*1024*1024), // 增大接收缓冲至 50 MB
		),
		grpc.WithKeepaliveParams(keepalive.ClientParameters{
			Time:                10 * time.Second, // 每 10s 发一次 ping
			Timeout:             3 * time.Second,  // ping 超时
			PermitWithoutStream: true,             // 空闲时也保活
		}),
	)
	if err != nil {
		slog.Error("failed to connect to AI service", "error", err)
		os.Exit(1)
	}
	defer conn.Close()

	irisClient := irisv1.NewIrisPredictorClient(conn)
	modelClient := modelv1.NewModelPredictorClient(conn)

	// 1. 定义全局对象池
	var predictReqPool = sync.Pool{
		New: func() interface{} {
			return new(irisv1.IrisPredictRequest) // 篮子空了才创建新的
		},
	}

	r := gin.Default()

	r.GET("/metrics", gin.WrapH(promhttp.Handler()))

	// 健康检查端点，供 K8s readiness/liveness 探针使用
	r.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	})

	//iris
	r.POST("/predict/iris", func(c *gin.Context) {
		timer := prometheus.NewTimer(httpDuration.WithLabelValues("/predict/iris"))
		defer timer.ObserveDuration()

		// ✓ bind into a plain struct first — proto structs don't have json tags
		var body struct {
			SepalLength float32 `json:"sepal_length"`
			SepalWidth  float32 `json:"sepal_width"`
			PetalLength float32 `json:"petal_length"`
			PetalWidth  float32 `json:"petal_width"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			httpRequestsTotal.WithLabelValues("/predict/iris", "400").Inc()
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return
		}
		// ✓ correct type assertion
		req := predictReqPool.Get().(*irisv1.IrisPredictRequest)
		defer func() {
			req.Reset()
			predictReqPool.Put(req)
		}()

		// copy fields from plain struct into proto request
		req.SepalLength = body.SepalLength
		req.SepalWidth  = body.SepalWidth
		req.PetalLength = body.PetalLength
		req.PetalWidth  = body.PetalWidth

		ctx, cancel := context.WithTimeout(c.Request.Context(), 3*time.Second)
		defer cancel()

		grpcStart := time.Now()
		// ✓ irisClient, not client
		resp, err := irisClient.IrisPredict(ctx, req)
		grpcStatus := "ok"
		if err != nil {
			grpcStatus = "error"
		}
		grpcRequestDuration.WithLabelValues("IrisPredict", grpcStatus).Observe(time.Since(grpcStart).Seconds())

		if err != nil {
			httpRequestsTotal.WithLabelValues("/predict/iris", "500").Inc()
			slog.Error("iris service call failed", "error", err)
			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return
		}

		httpRequestsTotal.WithLabelValues("/predict/iris", "200").Inc()
		c.JSON(http.StatusOK, gin.H{
			"result": resp.ClassName,
			"id":     resp.ClassId,
			"source": "Go Gateway -> Python AI (Iris)",
		})

	})

	//models qwen
	r.POST("/predict/model", func(c *gin.Context) {

		timer := prometheus.NewTimer(httpDuration.WithLabelValues("/predict/model"))
		defer timer.ObserveDuration()

		var reqJson struct {
			Prompt string `json:"prompt" binding:"required"`
		}
		if err := c.ShouldBindJSON(&reqJson); err != nil {
			httpRequestsTotal.WithLabelValues("/predict/model", "400").Inc()
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return
		}
		if len(reqJson.Prompt) > 2000 {
			httpRequestsTotal.WithLabelValues("/predict/model", "400").Inc()
			c.JSON(http.StatusBadRequest, gin.H{"error": "prompt exceeds maximum length of 2000 characters"})
			return
		}

		ctx, cancel := context.WithTimeout(c.Request.Context(), 60*time.Second)
		defer cancel()

		// ✅ Add this — time the gRPC call
		grpcStart := time.Now()
		resp, err := modelClient.ModelPredict(ctx, &modelv1.ModelPredictRequest{
			Prompt: reqJson.Prompt,
		})
		grpcStatus := "ok"
		if err != nil {
			grpcStatus = "error"
		}
		grpcRequestDuration.WithLabelValues("ModelPredict", grpcStatus).
        Observe(time.Since(grpcStart).Seconds())

		if err != nil {
			httpRequestsTotal.WithLabelValues("/predict/model", "500").Inc()
			slog.Error("model service call failed", "error", err)
			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return
		}

		// === 新增：记录大模型专属指标 ===
		if resp.EvalCount > 0 {
			// 累加生成的 Token 数
			aiTokensTotal.WithLabelValues(resp.ModelName).Add(float64(resp.EvalCount))

			// Ollama 的 eval_duration 单位通常是纳秒，转换为秒
			durationSec := float64(resp.EvalDuration) / 1e9
			aiGenerationDuration.WithLabelValues(resp.ModelName).Observe(durationSec)
		}

		httpRequestsTotal.WithLabelValues("/predict/model", "200").Inc()
		c.JSON(http.StatusOK, gin.H{
			"reply":  resp.Response,
			"model":  resp.ModelName,
			// 可选：把指标也返回给前端展示
			"metrics": gin.H{
				"prompt_tokens": resp.PromptEvalCount,
				"output_tokens": resp.EvalCount,
				"duration_sec":  float64(resp.EvalDuration) / 1e9,
			},
			"source": "Go Gateway -> Ollama (Qwen)",
		})
	})

	slog.Info("Go Gateway running on http://localhost:8080")

	srv := &http.Server{
		Addr:    ":8080",
		Handler: r,
	}

	// 在独立 goroutine 中启动 HTTP 服务器
	go func() {
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			slog.Error("HTTP server error", "error", err)
			os.Exit(1)
		}
	}()

	// 等待终止信号（SIGTERM/SIGINT），实现优雅关闭
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	slog.Info("Shutting down server gracefully...")

	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer shutdownCancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		slog.Error("Server forced to shutdown", "error", err)
	}
	slog.Info("Server stopped.")
} */

package main

import (
	"context"
	"log/slog"
	"net/http"
	_ "net/http/pprof"
	"os"
	"os/signal"
	"syscall"

	"my-go-gateway/config"
	irisv1 "my-go-gateway/gen/iris/v1"
	modelv1 "my-go-gateway/gen/model/v1"
	"my-go-gateway/grpcclient"
	"my-go-gateway/handlers"
	"my-go-gateway/metrics"
	"my-go-gateway/router"
	"my-go-gateway/telemetry"
)

func main() {
	cfg := config.Load()

	// pprof on a separate port
	go func() {
		slog.Info("pprof running", "addr", "http://localhost"+cfg.PProfAddr+"/debug/pprof")
		if err := http.ListenAndServe(cfg.PProfAddr, nil); err != nil {
			slog.Error("pprof failed", "error", err)
		}
	}()

	// Metrics
	metrics.Register()

	// Tracing
	tp, err := telemetry.InitTracer(context.Background(), cfg.JaegerEndpoint)
	if err != nil {
		slog.Error("failed to initialize tracer", "error", err)
		os.Exit(1)
	}
	defer func() { _ = tp.Shutdown(context.Background()) }()

	// gRPC connection
	conn, err := grpcclient.Dial(cfg)
	if err != nil {
		slog.Error("failed to connect to AI service", "error", err)
		os.Exit(1)
	}
	defer conn.Close()

	// Handlers
	healthHandler := handlers.NewHealthHandler()
	irisHandler := handlers.NewIrisHandler(irisv1.NewIrisPredictorClient(conn), cfg)
	modelHandler := handlers.NewModelHandler(modelv1.NewModelPredictorClient(conn), cfg)

	// Router
	r := router.Setup(healthHandler, irisHandler, modelHandler)

	srv := &http.Server{Addr: cfg.HTTPAddr, Handler: r}

	go func() {
		slog.Info("Go Gateway running", "addr", cfg.HTTPAddr)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			slog.Error("HTTP server error", "error", err)
			os.Exit(1)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	slog.Info("Shutting down gracefully...")
	shutdownCtx, cancel := context.WithTimeout(context.Background(), cfg.GRPCKeepAliveTimeout)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		slog.Error("forced shutdown", "error", err)
	}
	slog.Info("Server stopped.")
}

/* ```
The final package layout:

service_go/
├── main.go
├── config/
│   └── config.go          # all env vars + typed defaults
├── telemetry/
│   └── tracer.go          # initTracer, no globals
├── metrics/
│   └── metrics.go         # all prometheus vars + Register()
├── grpcclient/
│   └── client.go          # Dial() — keepalive, otelgrpc, msg size
├── handlers/
│   ├── health.go
│   ├── iris.go            # owns sync.Pool, timeout from cfg
│   └── model.go           # owns token metrics logic
└── router/
    └── router.go          # pure route wiring, no business logic
``` */
