package main

import (
	"context"
	"log/slog"
	"net/http"
	"os"
	"sync"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/keepalive"

	_ "net/http/pprof"
	// --- OpenTelemetry tracing ---
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
	"go.opentelemetry.io/otel/propagation"
	"go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	semconv "go.opentelemetry.io/otel/semconv/v1.17.0"

	irisv1 "my-go-gateway/gen/iris/v1"
	modelv1 "my-go-gateway/gen/model/v1"

	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
)

var (
	// Total HTTP requests (used to calculate QPS)
	httpRequestsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "http_requests_total",
			Help: "Total number of HTTP requests.",
		},
		[]string{"path", "status"},
	)
	// Request latency histogram (used to calculate P99 latency)
	httpDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "http_request_duration_seconds",
			Help:    "Histogram of response latency for HTTP requests.",
			Buckets: []float64{.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10},
		},
		[]string{"path"},
	)

	grpcRequestDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "grpc_request_duration_seconds",
			Help:    "Histogram of gRPC request duration.",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"method", "status"},
	)

	// AI model metrics
	// Total tokens generated (used to calculate throughput TPS)
	aiTokensTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "ai_generated_tokens_total",
			Help: "Total number of tokens generated by AI models.",
		},
		[]string{"model"},
	)
	// Pure inference latency for the LLM
	aiGenerationDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "ai_generation_duration_seconds",
			Help:    "Histogram of AI model purely generation duration.",
			Buckets: []float64{.5, 1, 2, 5, 10, 20, 30, 60},
		},
		[]string{"model"},
	)
)

func init() {
	prometheus.MustRegister(httpRequestsTotal)
	prometheus.MustRegister(httpDuration)
	prometheus.MustRegister(grpcRequestDuration)
	prometheus.MustRegister(aiTokensTotal)
	prometheus.MustRegister(aiGenerationDuration)
}

// initTracer initialises the OpenTelemetry tracer and connects to Jaeger.
func initTracer() (*sdktrace.TracerProvider, error) {
	ctx := context.Background()

	jaegerEndpoint := os.Getenv("JAEGER_ENDPOINT")
	if jaegerEndpoint == "" {
		jaegerEndpoint = "localhost:4317" // local dev fallback
	}

	exporter, err := otlptracegrpc.New(ctx,
		otlptracegrpc.WithEndpoint(jaegerEndpoint),
		otlptracegrpc.WithInsecure(),
	)
	if err != nil {
		return nil, err
	}

	tp := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(exporter),
		sdktrace.WithResource(resource.NewWithAttributes(
			semconv.SchemaURL,
			semconv.ServiceNameKey.String("go-gateway"),
		)),
	)

	otel.SetTracerProvider(tp)
	// W3C TraceContext propagation so otelgrpc can forward trace IDs downstream.
	otel.SetTextMapPropagator(propagation.TraceContext{})
	return tp, nil
}

func main() {

	go func() {
		slog.Info("pprof running on http://localhost:6060/debug/pprof")
		if err := http.ListenAndServe(":6060", nil); err != nil {
			slog.Error("pprof failed", "error", err)
		}
	}()

	// 1. Initialise distributed tracing
	tp, err := initTracer()
	if err != nil {
		slog.Error("failed to initialize tracer", "error", err)
		os.Exit(1)
	}
	defer func() { _ = tp.Shutdown(context.Background()) }()

	addr := os.Getenv("AI_SERVICE_ADDR")
	if addr == "" {
		addr = "localhost:50051" // local dev fallback
	}
	conn, err := grpc.NewClient(
		addr,
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithStatsHandler(otelgrpc.NewClientHandler()),
		grpc.WithKeepaliveParams(keepalive.ClientParameters{
			Time:                10 * time.Second,
			Timeout:             3 * time.Second,
			PermitWithoutStream: true,
		}),
	)
	if err != nil {
		slog.Error("failed to connect to AI service", "error", err)
		os.Exit(1)
	}
	defer conn.Close()

	irisClient := irisv1.NewIrisPredictorClient(conn)
	modelClient := modelv1.NewModelPredictorClient(conn)

	// Object pool: reuse proto request structs to reduce GC pressure.
	var predictReqPool = sync.Pool{
		New: func() interface{} {
			return new(irisv1.IrisPredictRequest)
		},
	}

	r := gin.Default()

	// Health check used by Kubernetes liveness and readiness probes.
	r.GET("/healthz", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	})

	r.GET("/metrics", gin.WrapH(promhttp.Handler()))

	// Iris flower classification
	r.POST("/predict/iris", func(c *gin.Context) {
		timer := prometheus.NewTimer(httpDuration.WithLabelValues("/predict/iris"))
		defer timer.ObserveDuration()

		// Bind into a plain struct first — proto structs don't have json tags.
		var body struct {
			SepalLength float32 `json:"sepal_length"`
			SepalWidth  float32 `json:"sepal_width"`
			PetalLength float32 `json:"petal_length"`
			PetalWidth  float32 `json:"petal_width"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			httpRequestsTotal.WithLabelValues("/predict/iris", "400").Inc()
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return
		}

		req := predictReqPool.Get().(*irisv1.IrisPredictRequest)
		defer func() {
			req.Reset()
			predictReqPool.Put(req)
		}()

		req.SepalLength = body.SepalLength
		req.SepalWidth = body.SepalWidth
		req.PetalLength = body.PetalLength
		req.PetalWidth = body.PetalWidth

		ctx, cancel := context.WithTimeout(c.Request.Context(), 3*time.Second)
		defer cancel()

		grpcStart := time.Now()
		resp, err := irisClient.IrisPredict(ctx, req)
		grpcStatus := "ok"
		if err != nil {
			grpcStatus = "error"
		}
		grpcRequestDuration.WithLabelValues("IrisPredict", grpcStatus).Observe(time.Since(grpcStart).Seconds())

		if err != nil {
			httpRequestsTotal.WithLabelValues("/predict/iris", "500").Inc()
			slog.Error("iris service call failed", "error", err)
			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return
		}

		httpRequestsTotal.WithLabelValues("/predict/iris", "200").Inc()
		c.JSON(http.StatusOK, gin.H{
			"result": resp.ClassName,
			"id":     resp.ClassId,
			"source": "Go Gateway -> Python AI (Iris)",
		})
	})

	// LLM inference via Ollama (qwen2.5)
	r.POST("/predict/model", func(c *gin.Context) {
		timer := prometheus.NewTimer(httpDuration.WithLabelValues("/predict/model"))
		defer timer.ObserveDuration()

		var reqJson struct {
			Prompt string `json:"prompt" binding:"required"`
		}
		if err := c.ShouldBindJSON(&reqJson); err != nil {
			httpRequestsTotal.WithLabelValues("/predict/model", "400").Inc()
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return
		}

		ctx, cancel := context.WithTimeout(c.Request.Context(), 60*time.Second)
		defer cancel()

		grpcStart := time.Now()
		resp, err := modelClient.ModelPredict(ctx, &modelv1.ModelPredictRequest{
			Prompt: reqJson.Prompt,
		})
		grpcStatus := "ok"
		if err != nil {
			grpcStatus = "error"
		}
		grpcRequestDuration.WithLabelValues("ModelPredict", grpcStatus).
			Observe(time.Since(grpcStart).Seconds())

		if err != nil {
			httpRequestsTotal.WithLabelValues("/predict/model", "500").Inc()
			slog.Error("model service call failed", "error", err)
			c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return
		}

		// Record AI-specific metrics.
		if resp.EvalCount > 0 {
			aiTokensTotal.WithLabelValues(resp.ModelName).Add(float64(resp.EvalCount))
			// Ollama eval_duration is in nanoseconds; convert to seconds.
			durationSec := float64(resp.EvalDuration) / 1e9
			aiGenerationDuration.WithLabelValues(resp.ModelName).Observe(durationSec)
		}

		httpRequestsTotal.WithLabelValues("/predict/model", "200").Inc()
		c.JSON(http.StatusOK, gin.H{
			"reply": resp.Response,
			"model": resp.ModelName,
			"metrics": gin.H{
				"prompt_tokens": resp.PromptEvalCount,
				"output_tokens": resp.EvalCount,
				"duration_sec":  float64(resp.EvalDuration) / 1e9,
			},
			"source": "Go Gateway -> Ollama (Qwen)",
		})
	})

	slog.Info("Go Gateway running on http://localhost:8080")
	r.Run(":8080")
}
