package metrics

import "github.com/prometheus/client_golang/prometheus"

var (
	HTTPRequestsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "http_requests_total",
			Help: "Total number of HTTP requests.",
		},
		[]string{"path", "status"},
	)

	HTTPDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "http_request_duration_seconds",
			Help:    "Histogram of response latency for HTTP requests.",
			Buckets: []float64{.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10},
		},
		[]string{"path"},
	)

	GRPCRequestDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "grpc_request_duration_seconds",
			Help:    "Histogram of gRPC request duration.",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"method", "status"},
	)

	AITokensTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "ai_generated_tokens_total",
			Help: "Total number of tokens generated by AI models.",
		},
		[]string{"model"},
	)

	AIGenerationDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "ai_generation_duration_seconds",
			Help:    "Histogram of AI model purely generation duration.",
			Buckets: []float64{.5, 1, 2, 5, 10, 20, 30, 60},
		},
		[]string{"model"},
	)
)

func Register() {
	prometheus.MustRegister(
		HTTPRequestsTotal,
		HTTPDuration,
		GRPCRequestDuration,
		AITokensTotal,
		AIGenerationDuration,
	)
}